class_name CheatCode
extends Resource

enum KeyCode {
	ArrowUp = KEY_UP,
	ArrowDown = KEY_DOWN,
	ArrowLeft = KEY_LEFT,
	ArrowRight = KEY_RIGHT,
	KeyA = KEY_A,
	KeyB = KEY_B,
	KeyC = KEY_C,
	KeyD = KEY_D,
	KeyE = KEY_E,
	KeyF = KEY_F,
	KeyG = KEY_G,
	KeyH = KEY_H,
	KeyI = KEY_I,
	KeyJ = KEY_J,
	KeyK = KEY_K,
	KeyL = KEY_L,
	KeyM = KEY_M,
	KeyN = KEY_N,
	KeyO = KEY_O,
	KeyP = KEY_P,
	KeyQ = KEY_Q,
	KeyR = KEY_R,
	KeyS = KEY_S,
	KeyT = KEY_T,
	KeyU = KEY_U,
	KeyV = KEY_V,
	KeyW = KEY_W,
	KeyX = KEY_X,
	KeyY = KEY_Y,
	KeyZ = KEY_Z,
	Key1 = KEY_1,
	Key2 = KEY_2,
	Key3 = KEY_3,
	Key4 = KEY_4,
	Key5 = KEY_5,
	Key6 = KEY_6,
	Key7 = KEY_7,
	Key8 = KEY_8,
	Key9 = KEY_9,
	Key0 = KEY_0,
	KeyEnter = KEY_ENTER,
	KeyEscape = KEY_ESCAPE,
	KeyShift = KEY_SHIFT,
	KeyBackspace = KEY_BACKSPACE,
	KeySpace = KEY_SPACE,
	KeyTab = KEY_TAB,
}

export (Array, KeyCode) var entries
